Task 1.1 : Write a function to compute 5/0 and use try/except to catch the exceptions.

In [7]:
try:
    div=5/0
    print(div)
except:
    print("can't divide number by zero")

can't divide number by zero


task 1.2 : Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
Hint: Subject,Verb and Object should be declared in the program as shown below.

subjects=["Americans ","Indians"]

verbs=["play","watch"]

objects=["Baseball","Cricket"]

Output should come as below:

Americans play Baseball.

Americans play Cricket.

Americans watch Baseball.

Americans watch Cricket.

Indians play Baseball.

Indians play Cricket.

Indians watch Baseball.

Indians watch Cricket.

In [19]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i,j,k)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


Task 2.1 : Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [30]:
import numpy as np
def matrix_generator(N,increasing):
    x=np.array([1,2,3,4])
    

    if increasing==False:
        return np.vander(x,N)
    elif increasing==True:
        return np.vander(x,N,increasing=True)


print(matrix_generator(3,True))
print(matrix_generator(3,False))

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]
